#!/usr/bin/env python3

import rospy
from onrobot_rg_control.msg import OnRobotRGInput


def printStatus(status):
    """Prints the status string generated by the statusInterpreter function."""

    rospy.loginfo(statusInterpreter(status))


def OnRobotRGStatusListener():
    """Initializes the node and subscribe to the OnRobotRGInput topic."""

    rospy.init_node('OnRobotRGStatusListener', log_level=rospy.DEBUG)
    rospy.Subscriber("OnRobotRGInput", OnRobotRGInput, printStatus)
    rospy.spin()


def statusInterpreter(status):
    """Generates a string according to the current value
       of the status variables.
    """

    output = '\n-----\nOnRobot RG status interpreter\n-----\n'

    # g_fof
    output += 'g_fof = ' + str(status.g_fof) + ': '
    output += 'Current fingertip offset: ' + str(status.g_fof / 10.0) + ' mm\n'

    # g_gwd
    output += 'g_gwd = ' + str(status.g_gwd) + ': '
    output += 'Current width between the gripper fingers (w/o offset): ' + \
              str(status.g_gwd / 10.0) + ' mm\n'

    # g_sta
    output += 'g_sta = ' + str(status.g_sta) + ': '
    g_sta16bit = format(status.g_sta, '016b')
    output += '(g_sta (16 bit) = ' + g_sta16bit + '), Currtent states: '
    if int(g_sta16bit[-1]):
        output += ' A motion is ongoing so new commands are not accepted.'
    if int(g_sta16bit[-2]):
        output += ' An internal- or external grip is detected.'
    if int(g_sta16bit[-3]):
        output += ' Safety switch 1 is pushed.'
    if int(g_sta16bit[-4]):
        output += ' Safety circuit 1 is activated so the gripper cannot move.'
    if int(g_sta16bit[-5]):
        output += ' Safety switch 2 is pushed.'
    if int(g_sta16bit[-6]):
        output += ' Safety circuit 2 is activated so the gripper cannot move.'
    if int(g_sta16bit[-7]):
        output += ' Any of the safety switch is pushed.'

    # gWDF
    output += '\ngWDF = ' + str(status.gWDF) + ': '
    output += 'Current width between the gripper fingers (w offset): ' + \
              str(status.gWDF / 10.0) + ' mm\n'

    return output


if __name__ == '__main__':
    OnRobotRGStatusListener()
